project:
  type: website
  
format: 
  html:
    webR: true 
  
website:
  page-navigation: true
  title: "Bass Connections Summer Exercises"
  search: true
  reader-mode: true
  site-url: "https://kathusar.github.io/bass_summer_exercises/"
  repo-url: https://github.com/KatHusar/bass_summer_exercises
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exercises/ch1.qmd
        text: Exercises
  sidebar:
    style: "floating"
    contents:
      - section: "Content"
        contents:
          - index.qmd
          - exercises/ch1.qmd
          - exercises/ch3.qmd
          - exercises/ch5.qmd

  page-footer: 
    left: "Built using Quarto Webr."
    right: 
      - icon: github
        href: https://github.com/coatless/quarto-webr

# Set the language that should be used for Quarto websites
# https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/language
# lang: en

# Set default options for every webpage that may or may not include webR.
webr: 
  show-startup-message: false    # Display status of webR initialization
#  show-header-message: false     # Check to see if COOP&COEP headers are set for speed.
  packages: ['ggplot2', 'dplyr'] # Pre-install dependencies
#  base-url: ''                   # Base URL used for specifying where R WebAssembly binaries should be located

# Attach webR to every page
filters:
  - webr
