name: Deploy Quarto Site 

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: quarto-dev/quarto-actions/render@v2
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: bass-su2025/bass-su2025.github.io
          publish_dir: ./_site
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
